2019-04-25 10:50:31 [main] WARN  UserDAOImplementation:117 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delete from users where user_id=2' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delete from users where user_id=2' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.delete(UserDAOImplementation.java:112) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testDelete(UserDAOImplementationTest.java:51) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-25 10:50:51 [main] WARN  UserDAOImplementation:117 - Can not issue data manipulation statements with executeQuery().
java.sql.SQLException: Can not issue data manipulation statements with executeQuery().
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.StatementImpl.checkForDml(StatementImpl.java:469) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1968) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.delete(UserDAOImplementation.java:112) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testDelete(UserDAOImplementationTest.java:51) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 09:43:26 [main] WARN  UserDAOImplementation:138 - Duplicate entry 'Vladimir11' for key 'username'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Vladimir11' for key 'username'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.add(UserDAOImplementation.java:133) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testAdd(UserDAOImplementationTest.java:66) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 12:41:40 [main] WARN  UserDAOImplementation:47 - Column 'email' not found.
java.sql.SQLException: Column 'email' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.JDBC4ResultSet.getNString(JDBC4ResultSet.java:232) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.get(UserInfoDAOImplementation.java:37) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testGet(UserInfoDAOImplementationTest.java:23) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 13:58:33 [main] WARN  UserDAOImplementation:47 - Column 'email' not found.
java.sql.SQLException: Column 'email' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.JDBC4ResultSet.getNString(JDBC4ResultSet.java:232) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.get(UserInfoDAOImplementation.java:37) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testGet(UserInfoDAOImplementationTest.java:23) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 13:59:32 [main] WARN  UserDAOImplementation:47 - Column 'email' not found.
java.sql.SQLException: Column 'email' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.JDBC4ResultSet.getNString(JDBC4ResultSet.java:232) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.get(UserInfoDAOImplementation.java:37) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testGet(UserInfoDAOImplementationTest.java:23) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 14:01:05 [main] WARN  UserDAOImplementation:47 - Column 'email' not found.
java.sql.SQLException: Column 'email' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5175) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.get(UserInfoDAOImplementation.java:37) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testGet(UserInfoDAOImplementationTest.java:23) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-26 14:09:30 [main] WARN  UserDAOImplementation:91 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.delete(UserInfoDAOImplementation.java:88) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testDelete(UserInfoDAOImplementationTest.java:39) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:25:39 [main] WARN  UserDAOImplementation:91 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.delete(UserInfoDAOImplementation.java:88) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testDelete(UserInfoDAOImplementationTest.java:39) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:29:29 [main] WARN  UserDAOImplementation:91 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.delete(UserInfoDAOImplementation.java:88) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testDelete(UserInfoDAOImplementationTest.java:39) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:35:26 [main] WARN  UserDAOImplementation:124 - Cannot add or update a child row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`petshelter`.`users`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `userinfo` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.add(UserDAOImplementation.java:121) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testAdd(UserDAOImplementationTest.java:66) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:37:51 [main] WARN  UserDAOImplementation:92 - Unknown column 'users.user_id' in 'field list'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'users.user_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.getAll(UserDAOImplementation.java:81) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGetAll(UserDAOImplementationTest.java:37) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:40:13 [main] WARN  UserDAOImplementation:67 - Unknown column 'user_id' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'user_id' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:57) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:22) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 11:45:04 [main] WARN  UserDAOImplementation:106 - Unknown column 'user_id' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'user_id' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.delete(UserDAOImplementation.java:103) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testDelete(UserDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:03:15 [main] WARN  UserDAOImplementation:106 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.delete(UserDAOImplementation.java:103) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testDelete(UserDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:03:44 [main] WARN  UserDAOImplementation:106 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.delete(UserDAOImplementation.java:103) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testDelete(UserDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:04:01 [main] WARN  UserDAOImplementation:123 - Duplicate entry 'Vladimir11' for key 'username'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Vladimir11' for key 'username'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.add(UserDAOImplementation.java:120) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testAdd(UserDAOImplementationTest.java:66) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:04:35 [main] WARN  UserDAOImplementation:91 - Unknown column 'id' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.delete(UserInfoDAOImplementation.java:88) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testDelete(UserInfoDAOImplementationTest.java:39) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:05:10 [main] WARN  UserDAOImplementation:91 - Unknown column 'id' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.delete(UserInfoDAOImplementation.java:88) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testDelete(UserInfoDAOImplementationTest.java:39) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:54:25 [main] WARN  UserInfoDAOImplementation:113 - Parameter index out of range (7 > number of parameters, which is 6).
java.sql.SQLException: Parameter index out of range (7 > number of parameters, which is 6).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3367) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3352) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3391) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setLong(PreparedStatement.java:3408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.add(UserInfoDAOImplementation.java:109) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testAdd(UserInfoDAOImplementationTest.java:72) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:54:57 [main] WARN  UserInfoDAOImplementation:113 - Table 'petshelter.usersinfo' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'petshelter.usersinfo' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.add(UserInfoDAOImplementation.java:110) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testAdd(UserInfoDAOImplementationTest.java:72) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 12:55:16 [main] WARN  UserInfoDAOImplementation:113 - Cannot add or update a child row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`petshelter`.`userinfo`, CONSTRAINT `fk_users_userid` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.add(UserInfoDAOImplementation.java:110) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testAdd(UserInfoDAOImplementationTest.java:72) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 13:15:54 [main] WARN  UserDAOImplementation:123 - Duplicate entry 'Vladimir11' for key 'username'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Vladimir11' for key 'username'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.add(UserDAOImplementation.java:120) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testAdd(UserDAOImplementationTest.java:66) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 13:20:25 [main] WARN  UserInfoDAOImplementation:113 - Duplicate entry '1' for key 'user_id'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'user_id'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.add(UserInfoDAOImplementation.java:110) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testAdd(UserInfoDAOImplementationTest.java:72) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 13:31:50 [main] WARN  UserInfoDAOImplementation:139 - No value specified for parameter 8
java.sql.SQLException: No value specified for parameter 8
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2256) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2236) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2103) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.update(UserInfoDAOImplementation.java:136) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testUpdate(UserInfoDAOImplementationTest.java:101) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 13:32:33 [main] WARN  UserInfoDAOImplementation:140 - Unknown column 'users.email' in 'field list'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'users.email' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementation.update(UserInfoDAOImplementation.java:137) [classes/:?]
	at by.training.finaltask.dao.mysql.UserInfoDAOImplementationTest.testUpdate(UserInfoDAOImplementationTest.java:101) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 16:11:57 [main] WARN  AdoptionImplementation:149 - Column 'user_id' specified twice
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column 'user_id' specified twice
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.AdoptionDAOImplementation.add(AdoptionImplementation.java:146) [classes/:?]
	at by.training.finaltask.dao.mysql.AdoptionDAOImplementationTest.testAdd(AdoptionDAOImplementationTest.java:63) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-27 17:20:55 [main] WARN  AdoptionImplementation:196 - Parameter index out of range (2 > number of parameters, which is 1).
java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3367) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3352) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3391) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setDate(PreparedStatement.java:3277) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setDate(PreparedStatement.java:3250) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.AdoptionDAOImplementation.delete(AdoptionImplementation.java:190) [classes/:?]
	at by.training.finaltask.dao.mysql.AdoptionDAOImplementationTest.testDelete1(AdoptionDAOImplementationTest.java:84) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-29 12:10:31 [main] WARN  PetDAOImplementation:105 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.PetDAOImplementation.delete(PetDAOImplementation.java:102) [classes/:?]
	at by.training.finaltask.dao.mysql.PetDAOImplementationTest.testDelete(PetDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-29 12:11:45 [main] WARN  PetDAOImplementation:105 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.PetDAOImplementation.delete(PetDAOImplementation.java:102) [classes/:?]
	at by.training.finaltask.dao.mysql.PetDAOImplementationTest.testDelete(PetDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-29 12:14:17 [main] WARN  PetDAOImplementation:105 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.PetDAOImplementation.delete(PetDAOImplementation.java:102) [classes/:?]
	at by.training.finaltask.dao.mysql.PetDAOImplementationTest.testDelete(PetDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-29 12:16:13 [main] WARN  PetDAOImplementation:105 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.PetDAOImplementation.delete(PetDAOImplementation.java:102) [classes/:?]
	at by.training.finaltask.dao.mysql.PetDAOImplementationTest.testDelete(PetDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-29 12:18:48 [main] WARN  PetDAOImplementation:105 - Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`petshelter`.`adoptions_made`, CONSTRAINT `fk_petid` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.PetDAOImplementation.delete(PetDAOImplementation.java:102) [classes/:?]
	at by.training.finaltask.dao.mysql.PetDAOImplementationTest.testDelete(PetDAOImplementationTest.java:52) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
