2019-04-24 18:57:16 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 18:58:51 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 18:59:49 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:00:40 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:01:33 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:01:47 [main] WARN  UserDAOImplementation:56 - Parameter index out of range (1 > number of parameters, which is 0).
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3367) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3352) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3391) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3342) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:42) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:02:04 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:04:08 [main] WARN  UserDAOImplementation:56 - Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2094) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:05:49 [main] WARN  UserDAOImplementation:56 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'select users.user_id,users.username,users.password,users.role from users where u' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:06:17 [main] WARN  UserDAOImplementation:56 - Parameter index out of range (1 > number of parameters, which is 0).
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3367) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3352) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3391) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3342) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:42) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:06:24 [main] WARN  UserDAOImplementation:56 - Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2094) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:43) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
2019-04-24 19:11:20 [main] WARN  UserDAOImplementation:53 - Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.StatementImpl.getGeneratedKeys(StatementImpl.java:1693) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at by.training.finaltask.dao.mysql.UserDAOImplementation.get(UserDAOImplementation.java:39) [classes/:?]
	at by.training.finaltask.dao.mysql.UserDAOImplementationTest.testGet(UserDAOImplementationTest.java:20) [Task_FinalProject_WebApplication/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0-beta3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:763) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:594) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:304) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.0.0-beta3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:997) [testng-7.0.0-beta3.jar:?]
	at org.testng.TestNG.run(TestNG.java:965) [testng-7.0.0-beta3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
